### PR TITLE
Ioannis dev temp

### PR DESCRIPTION
**Pull request by ioannismarios**
Targets needed for cucr_robot_tests ros2 franka demo. ioannis_dev_temp also reverted the changes from goal regions branch (check that all targets are as expected)

### CODE REVIEW

**Comment by frkndmn** [comment]
Hi @ioannismarios,

I've removed the goal region implementation from the branch (please take a look). I successfully tested this branch in ros1. However I am not able to test in ros2. After testing in ros2, we can merge it. Thanks.

**Comment by jjpatino-byte** [comment]
Hi @ioannismarios! I have checked the last updates and there are some problems with the simulation in Gazebo, Gazebo is not showing the Franka link meshes. The rest of the thing are ok. Also I remember that in the ROS1 implementation, the planning group 'panda manipulator' had its end effector frame rotated 45 degrees with respect to the planning group "panda_arm", and also it was displaced to the hand TCP. However in this simulation, both frames seem to be the same. It would be nice if this can be changed (if possible), although it's not actually a big problem. RViz works fine. Let me know when this is fixed, so that I can test it and merge it, if it is ready.
image
image
image

**Comment by ioannismarios** [comment]
Hi @jjpatino-byte and @frkndmn, the problem with the meshes not showing up in gazebo is because @frkndmn made a change in my modified ros-test_franka_simulation_bringup/install.bash. I changed it back (keeping the change @frkndmn made to the unwanted special git repo) and it should now be working again. I am not sure what undid the link8 rotation though, we might look into that in the future if it ends up being an issue. @frkndmn, I re-added install.bash for the moveit task constructor as this is something I did for the ROS2 migration. Everything else seems to be okay, I think we can complete the pull request.

**Comment by jjpatino-byte** [comment]
@ioannismarios Everything seems to be working now. I'll merge the PR.

**Pull request merged**
